name: september24
favicon: null
layout_spectrum: 0.2032
typography_spectrum: 0.20174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#93bafd'
    - '#5e3b12'
    - '#896c3a'
  brandStrength: 1
  lightness: 0.6803119541145861
  saturation: 0.6875
  rhythmicContrast: 0.19385050632990897
purpose: []
